### ISSUE TITLE
测试时候有bug

### ISSUE THREAD

**Issue by puallee** [LiuLiluZJU/AI-Co-Pilot-Bronchoscope-Robot#3]
PS J:\AI-Co-Pilot-Bronchoscope-Robot-master>  python test.py --human
pybullet build time: Feb  4 2024 17:30:46
starting thread 0
started testThreads thread 0 with threadHandle 0000000000000F60
argc=2
argv[0] = --unused
argv[1] = --start_demo_name=Physics Server
ExampleBrowserThreadFunc started
Version = 4.6.0 NVIDIA 537.70
Vendor = NVIDIA Corporation
Renderer = NVIDIA RTX A4000/PCIe/SSE2
b3Printf: Selected demo: Physics Server
starting thread 0
started MotionThreads thread 0 with threadHandle 000000000000119C
MotionThreadFunc thread started
((-0.8732862396240234, -0.38964423370361334, 4.496852348327636), (1.0041863555908201, 2.237700988769531, 5.631377784729004))
[-0.02183733  0.98740115  5.300019  ]
[-0.46772948 -0.285903    5.17517421]
[254 169   0]
self.rand_roll: 0
theta_cone: 10.110831285468024
phi: 261.0062190515983
nearest_distance_to_centerline: 0.04413126853623198
key down
Direction: [0 0 1 0 0]
160000
123
Traceback (most recent call last):
  File "J:\AI-Co-Pilot-Bronchoscope-Robot-master\test.py", line 64, in <module>
    = simulator.run(args, net, model_dir=args.model_dir, net_transfer=None, transform_func=transforms_eval, training=False)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "J:\AI-Co-Pilot-Bronchoscope-Robot-master\lib\engine\onlineSimulation.py", line 644, in run
    rgb_img_bullet = rgb_img_bullet[:, :, :3]
                     ~~~~~~~~~~~~~~^^^^^^^^^^
TypeError: tuple indices must be integers or slices, not tuple
numActiveThreads = 0
stopping threads
Thread with taskId 0 with handle 000000000000119C exiting
Thread TERMINATED
finished
numActiveThreads = 0
btShutDownExampleBrowser stopping threads
Thread with taskId 0 with handle 0000000000000F60 exiting
Thread TERMINATED

**Comment by hankerbit** [comment]
i can run the code, but the "human" parameter  does not work. How can i reproduce the result using human command?
